@startuml ollama_llm_class
!include ../common/book-clean.puml


package "llm_agents_from_scratch.base.llm" <<Folder>> {
  abstract class BaseLLM {
    --
    +<<async>> complete(\n\t...\n): CompleteResponse\n
    +<<async>> chat(\n\t...\n): tuple[ChatMessage, ChatMessage]\n
    +<<async>> continue_chat_with_tool_results(\n\t...\n): tuple[list[ChatMessage], ChatMessage]\n
    +<<async>> structured_output<T>(\n\t...\n): T
  }
}

package "llm_agents_from_scratch.llms" <<Folder>> {

  class OllamaLLM {
    +model: str
    -_client: ~ollama.AsyncClient
    --
    +<<constructor>> __init__(\n\tmodel:str,\n\thost: str | None\n):
  }
}

' Relations
BaseLLM <|-- OllamaLLM : " inherits"

@enduml
