@startmindmap llm_agent_build_mental_model
!include ../common/book-clean.puml

* LLM Agent
**_ Part 3
*** MAS
**** Subagents
**** A2A

left side

**_ Part 1
*** Tools
**** SimpleFunction
**** PydanticFunction
*** LLM
**** Ollama
**_ Part 2
*** MCP Tools
*** Skills
*** Memory
*** Human in the Loop

@endmindmap
